"""Create db

Revision ID: 5ceb6f87d6d8
Revises: 
Create Date: 2024-05-12 21:53:57.403575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ceb6f87d6d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('count_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('id_month', sa.Integer(), nullable=True),
    sa.Column('id_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_day'], ['days.id'], ),
    sa.ForeignKeyConstraint(['id_month'], ['monthes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holiday')
    op.drop_table('monthes')
    op.drop_table('days')
    # ### end Alembic commands ###
